#!/usr/bin/env python3
"""Regenerate GameScripts.java after changing tests/headless_runtime.js or native_adapter.js."""
from pathlib import Path
import json
r=Path(__file__).resolve().parent.parent
menu=(r/'tests/headless_runtime.js').read_text()
adapter=(r/'tests/native_adapter.js').read_text()
boot="window.__DG_INSTALL_NATIVE=function(){if(window.__DG_NATIVE)return;var r=window.$DW||window.$hxClasses;if(!r||!r['co.doubleduck.dynamons3.meta.GameState'])return;if(!window.__DG_API){\n"+menu+"\n}\n"+adapter+"\n};window.__DG_INSTALL_NATIVE();"
native_boot="(function(){if(!window.__DG_NATIVE&&typeof window.__DG_INSTALL_NATIVE==='function')window.__DG_INSTALL_NATIVE();})();"
parts=[native_boot[i:i+6000] for i in range(0,len(native_boot),6000)]
s="package com.dynamongamer.royalvoid;\n\n/** Generated by tools/embed_runtime.py. */\npublic final class GameScripts {\n private static String cached;\n private GameScripts(){}\n public static synchronized String bootstrap(){if(cached!=null)return cached;StringBuilder b=new StringBuilder();\n"
s+=''.join('b.append('+json.dumps(p,ensure_ascii=True)+');\n' for p in parts)
s+='cached=b.toString();return cached;}\n}\n'
(r/'src/com/dynamongamer/royalvoid/GameScripts.java').write_text(s)
(r/'tests/bootstrap.js').write_text(boot)
print('DEX adapter: '+str(len(native_boot))+' characters; signed payload runtime: '+str(len(boot))+' characters')
