package com.dynamongamer.royalvoid;

/** Generated by tools/embed_runtime.py. */
public final class GameScripts {
 private static String cached;
 private GameScripts(){}
 public static synchronized String bootstrap(){if(cached!=null)return cached;StringBuilder b=new StringBuilder();
b.append("(function(){if(!window.__DG_NATIVE&&typeof window.__DG_INSTALL_NATIVE==='function')window.__DG_INSTALL_NATIVE();})();");
cached=b.toString();return cached;}
}
