/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ModsRouteImport } from './routes/mods'
import { Route as GeneratorRouteImport } from './routes/generator'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminNotificationsRouteImport } from './routes/admin-notifications'
import { Route as AdminLoaderRouteImport } from './routes/admin-loader'
import { Route as AdminKeysRouteImport } from './routes/admin-keys'
import { Route as AdminControlRouteImport } from './routes/admin-control'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModsIndexRouteImport } from './routes/mods.index'
import { Route as ModsSlugRouteImport } from './routes/mods.$slug'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsRoute = ModsRouteImport.update({
  id: '/mods',
  path: '/mods',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin-notifications',
  path: '/admin-notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoaderRoute = AdminLoaderRouteImport.update({
  id: '/admin-loader',
  path: '/admin-loader',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKeysRoute = AdminKeysRouteImport.update({
  id: '/admin-keys',
  path: '/admin-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminControlRoute = AdminControlRouteImport.update({
  id: '/admin-control',
  path: '/admin-control',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsIndexRoute = ModsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModsRoute,
} as any)
const ModsSlugRoute = ModsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ModsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/admin-control': typeof AdminControlRoute
  '/admin-keys': typeof AdminKeysRoute
  '/admin-loader': typeof AdminLoaderRoute
  '/admin-notifications': typeof AdminNotificationsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/favorites': typeof FavoritesRoute
  '/generator': typeof GeneratorRoute
  '/mods': typeof ModsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/unlock': typeof UnlockRoute
  '/mods/$slug': typeof ModsSlugRoute
  '/mods/': typeof ModsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/admin-control': typeof AdminControlRoute
  '/admin-keys': typeof AdminKeysRoute
  '/admin-loader': typeof AdminLoaderRoute
  '/admin-notifications': typeof AdminNotificationsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/favorites': typeof FavoritesRoute
  '/generator': typeof GeneratorRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/unlock': typeof UnlockRoute
  '/mods/$slug': typeof ModsSlugRoute
  '/mods': typeof ModsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/admin-control': typeof AdminControlRoute
  '/admin-keys': typeof AdminKeysRoute
  '/admin-loader': typeof AdminLoaderRoute
  '/admin-notifications': typeof AdminNotificationsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/favorites': typeof FavoritesRoute
  '/generator': typeof GeneratorRoute
  '/mods': typeof ModsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/unlock': typeof UnlockRoute
  '/mods/$slug': typeof ModsSlugRoute
  '/mods/': typeof ModsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/admin-control'
    | '/admin-keys'
    | '/admin-loader'
    | '/admin-notifications'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/favorites'
    | '/generator'
    | '/mods'
    | '/notifications'
    | '/profile'
    | '/unlock'
    | '/mods/$slug'
    | '/mods/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/admin-control'
    | '/admin-keys'
    | '/admin-loader'
    | '/admin-notifications'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/favorites'
    | '/generator'
    | '/notifications'
    | '/profile'
    | '/unlock'
    | '/mods/$slug'
    | '/mods'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/admin-control'
    | '/admin-keys'
    | '/admin-loader'
    | '/admin-notifications'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/favorites'
    | '/generator'
    | '/mods'
    | '/notifications'
    | '/profile'
    | '/unlock'
    | '/mods/$slug'
    | '/mods/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRoute
  AdminControlRoute: typeof AdminControlRoute
  AdminKeysRoute: typeof AdminKeysRoute
  AdminLoaderRoute: typeof AdminLoaderRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FavoritesRoute: typeof FavoritesRoute
  GeneratorRoute: typeof GeneratorRoute
  ModsRoute: typeof ModsRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods': {
      id: '/mods'
      path: '/mods'
      fullPath: '/mods'
      preLoaderRoute: typeof ModsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-notifications': {
      id: '/admin-notifications'
      path: '/admin-notifications'
      fullPath: '/admin-notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-loader': {
      id: '/admin-loader'
      path: '/admin-loader'
      fullPath: '/admin-loader'
      preLoaderRoute: typeof AdminLoaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-keys': {
      id: '/admin-keys'
      path: '/admin-keys'
      fullPath: '/admin-keys'
      preLoaderRoute: typeof AdminKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-control': {
      id: '/admin-control'
      path: '/admin-control'
      fullPath: '/admin-control'
      preLoaderRoute: typeof AdminControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods/': {
      id: '/mods/'
      path: '/'
      fullPath: '/mods/'
      preLoaderRoute: typeof ModsIndexRouteImport
      parentRoute: typeof ModsRoute
    }
    '/mods/$slug': {
      id: '/mods/$slug'
      path: '/$slug'
      fullPath: '/mods/$slug'
      preLoaderRoute: typeof ModsSlugRouteImport
      parentRoute: typeof ModsRoute
    }
  }
}

interface ModsRouteChildren {
  ModsSlugRoute: typeof ModsSlugRoute
  ModsIndexRoute: typeof ModsIndexRoute
}

const ModsRouteChildren: ModsRouteChildren = {
  ModsSlugRoute: ModsSlugRoute,
  ModsIndexRoute: ModsIndexRoute,
}

const ModsRouteWithChildren = ModsRoute._addFileChildren(ModsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRoute,
  AdminControlRoute: AdminControlRoute,
  AdminKeysRoute: AdminKeysRoute,
  AdminLoaderRoute: AdminLoaderRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  FavoritesRoute: FavoritesRoute,
  GeneratorRoute: GeneratorRoute,
  ModsRoute: ModsRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
